const catalog = {
  acousticbass1: {
    name: "Acoustic Bass",
    url: "sounds/acousticbass1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAD3RSTlMAhus/8uK4taCBYyAPzDhUH+aJAAAAbElEQVQI12NgYGAWU0o0YAACnn71mUU/DgBZT72AxJI4oFDsBiCL++oBBg5vBhDY0sBgv4CBWdCAgeszgxADg/z/jwwMigzpDMz///83YChj0GRgBLIEGCYhWAhZhA6EKQiTEbYhXIBwFcKlAA4eLfWnyic4AAAAAElFTkSuQmCC",
    buffer: null,
  },
  acousticbass2: {
    name: "Acoustic Bass",
    url: "sounds/acousticbass2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAD3RSTlMAhus/8uK4taCBYyAPzDhUH+aJAAAAbElEQVQI12NgYGAWU0o0YAACnn71mUU/DgBZT72AxJI4oFDsBiCL++oBBg5vBhDY0sBgv4CBWdCAgeszgxADg/z/jwwMigzpDMz///83YChj0GRgBLIEGCYhWAhZhA6EKQiTEbYhXIBwFcKlAA4eLfWnyic4AAAAAElFTkSuQmCC",
    buffer: null,
  },
  acousticbass3: {
    name: "Acoustic Bass",
    url: "sounds/acousticbass3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAD3RSTlMAhus/8uK4taCBYyAPzDhUH+aJAAAAbElEQVQI12NgYGAWU0o0YAACnn71mUU/DgBZT72AxJI4oFDsBiCL++oBBg5vBhDY0sBgv4CBWdCAgeszgxADg/z/jwwMigzpDMz///83YChj0GRgBLIEGCYhWAhZhA6EKQiTEbYhXIBwFcKlAA4eLfWnyic4AAAAAElFTkSuQmCC",
    buffer: null,
  },
  acousticsnare1: {
    name: "Acoustic Snare",
    url: "sounds/acousticsnare1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA2L2MiTf5BmDht94AAABGSURBVAjXY0gUhAAxBgEGCGBEZYUouUJYxR0dHeZglgWQ1QxisXaAQACQxQJmOQBZTGCWAoKFkEXogJuCMBnVNky3IFwKAOR6HvMp4o8LAAAAAElFTkSuQmCC",
    buffer: null,
  },
  acousticsnare2: {
    name: "Acoustic Snare",
    url: "sounds/acousticsnare2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA2L2MiTf5BmDht94AAABGSURBVAjXY0gUhAAxBgEGCGBEZYUouUJYxR0dHeZglgWQ1QxisXaAQACQxQJmOQBZTGCWAoKFkEXogJuCMBnVNky3IFwKAOR6HvMp4o8LAAAAAElFTkSuQmCC",
    buffer: null,
  },
  acousticsnare3: {
    name: "Acoustic Snare",
    url: "sounds/acousticsnare3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA2L2MiTf5BmDht94AAABGSURBVAjXY0gUhAAxBgEGCGBEZYUouUJYxR0dHeZglgWQ1QxisXaAQACQxQJmOQBZTGCWAoKFkEXogJuCMBnVNky3IFwKAOR6HvMp4o8LAAAAAElFTkSuQmCC",
    buffer: null,
  },
  bassdrum1: {
    name: "Bass Drum",
    url: "sounds/bassdrum1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  bassdrum2: {
    name: "Bass Drum",
    url: "sounds/bassdrum2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  bassdrum3: {
    name: "Bass Drum",
    url: "sounds/bassdrum3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  blank1: {
    name: "Blank",
    url: "sounds/blank1.wav",
    icon: "img/blank.png",
    buffer: null,
  },
  blank2: {
    name: "Blank",
    url: "sounds/blank2.wav",
    icon: "img/blank.png",
    buffer: null,
  },
  blank3: {
    name: "Blank",
    url: "sounds/blank3.wav",
    icon: "img/blank.png",
    buffer: null,
  },
  blank4: {
    name: "Blank",
    url: "sounds/blank4.wav",
    icon: "img/blank.png",
    buffer: null,
  },
  clap1: {
    name: "Clap",
    url: "sounds/clap1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  clap2: {
    name: "Clap",
    url: "sounds/clap2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  clap3: {
    name: "Clap",
    url: "sounds/clap3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  clap4: {
    name: "Clap",
    url: "sounds/clap4.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  clave1: {
    name: "Clave",
    url: "sounds/clave1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAWlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+aPZ0uAAAAHXRSTlMA6ICO+sogCWI5MxCnmnNRK/Ph3dU+FgcFuHtbSc8FjrAAAACHSURBVBjTZc/ZEsIgDIXhIFCWstTWLi7n/V9TLHZI9b/g4ptJMtC37hFTT7x8BSAGJn2Rkmb0Qo2NuirKNNpuOwViDR+7n09u7tnu/SfFT5KkupxSkjI6YnXItCBxSliIovJNvIrlXfU4HzKPet3HNYI3RMYH6GOxFcA0AcK2FcZZKa2rv34DAYgIN7N5/DUAAAAASUVORK5CYII=",
    buffer: null,
  },
  clave2: {
    name: "Clave",
    url: "sounds/clave2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAWlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+aPZ0uAAAAHXRSTlMA6ICO+sogCWI5MxCnmnNRK/Ph3dU+FgcFuHtbSc8FjrAAAACHSURBVBjTZc/ZEsIgDIXhIFCWstTWLi7n/V9TLHZI9b/g4ptJMtC37hFTT7x8BSAGJn2Rkmb0Qo2NuirKNNpuOwViDR+7n09u7tnu/SfFT5KkupxSkjI6YnXItCBxSliIovJNvIrlXfU4HzKPet3HNYI3RMYH6GOxFcA0AcK2FcZZKa2rv34DAYgIN7N5/DUAAAAASUVORK5CYII=",
    buffer: null,
  },
  clave3: {
    name: "Clave",
    url: "sounds/clave3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAWlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+aPZ0uAAAAHXRSTlMA6ICO+sogCWI5MxCnmnNRK/Ph3dU+FgcFuHtbSc8FjrAAAACHSURBVBjTZc/ZEsIgDIXhIFCWstTWLi7n/V9TLHZI9b/g4ptJMtC37hFTT7x8BSAGJn2Rkmb0Qo2NuirKNNpuOwViDR+7n09u7tnu/SfFT5KkupxSkjI6YnXItCBxSliIovJNvIrlXfU4HzKPet3HNYI3RMYH6GOxFcA0AcK2FcZZKa2rv34DAYgIN7N5/DUAAAAASUVORK5CYII=",
    buffer: null,
  },
  congaslap: {
    name: "Conga Slap",
    url: "sounds/congaslap.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAmdfGvrmik4tnAcKopZ1wX1pC5NHnKAAAAIhJREFUGNNtjksSxCAIREFFjd9E7n/XAao0s0gv5Pm6pIQd9Ju+1UpFzlGVnwU2GMXFIHhzMmVg6tJSo5ihkwxbcVyjKcVfJjt3jPc1BCLH7FqPcSAC4oixN1VEIVS//5f14TQ8ZlLLfB1Rklyow+sKKoYIkPg2Y6DKysfUslGHrVjwxuOmD/UDkJ8FVciAD1kAAAAASUVORK5CYII=",
    buffer: null,
  },
  crash1: {
    name: "Crash",
    url: "sounds/crash1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAhFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9tHAkSAAAAK3RSTlMAyZhYCLTm3gTyoH1tX1tEKBT20bukhXFTNxn87MasqZ+cjoB1TDwwHQ4M/GEISAAAAJlJREFUGNNdz0cSxCAMRFEZm+Cc4+QcdP/7DRIFi3kL/apmBThFwWnOLXi94Myp8UuLC1dKuiaxKtwo3/SeJAYy/JPBGltKxuSU2rMCeeODOxzBK3cfStIVYcoiTo1NmNTEmVRYGqy5hxFYHkUaI4aabg6lEFoJInGklGDtcyBXDd4Ln9z+Eqa5M+7rVZjkwFlwC9PNvdYCnB/Z3QqBTg1ErQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  crash2: {
    name: "Crash",
    url: "sounds/crash2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAhFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9tHAkSAAAAK3RSTlMAyZhYCLTm3gTyoH1tX1tEKBT20bukhXFTNxn87MasqZ+cjoB1TDwwHQ4M/GEISAAAAJlJREFUGNNdz0cSxCAMRFEZm+Cc4+QcdP/7DRIFi3kL/apmBThFwWnOLXi94Myp8UuLC1dKuiaxKtwo3/SeJAYy/JPBGltKxuSU2rMCeeODOxzBK3cfStIVYcoiTo1NmNTEmVRYGqy5hxFYHkUaI4aabg6lEFoJInGklGDtcyBXDd4Ln9z+Eqa5M+7rVZjkwFlwC9PNvdYCnB/Z3QqBTg1ErQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  crash3: {
    name: "Crash",
    url: "sounds/crash3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAhFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9tHAkSAAAAK3RSTlMAyZhYCLTm3gTyoH1tX1tEKBT20bukhXFTNxn87MasqZ+cjoB1TDwwHQ4M/GEISAAAAJlJREFUGNNdz0cSxCAMRFEZm+Cc4+QcdP/7DRIFi3kL/apmBThFwWnOLXi94Myp8UuLC1dKuiaxKtwo3/SeJAYy/JPBGltKxuSU2rMCeeODOxzBK3cfStIVYcoiTo1NmNTEmVRYGqy5hxFYHkUaI4aabg6lEFoJInGklGDtcyBXDd4Ln9z+Eqa5M+7rVZjkwFlwC9PNvdYCnB/Z3QqBTg1ErQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electricsnare1: {
    name: "Electric Snare",
    url: "sounds/electricsnare1.wav",
    icon: "img/electricsnare.png",
    buffer: null,
  },
  electricsnare2: {
    name: "Electric Snare",
    url: "sounds/electricsnare2.wav",
    icon: "img/electricsnare.png",
    buffer: null,
  },
  electricsnare3: {
    name: "Electric Snare",
    url: "sounds/electricsnare3.wav",
    icon: "img/electricsnare.png",
    buffer: null,
  },
  electroclap1: {
    name: "Electro Clap",
    url: "sounds/electroclap1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electroclap2: {
    name: "Electro Clap",
    url: "sounds/electroclap2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electroclap3: {
    name: "Electro Clap",
    url: "sounds/electroclap3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAMFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///0rtVBAAAAEHRSTlMAwiUcFikZK8Ygy78uh3Qww5McwgAAAG9JREFUCNdjuMkAAboMigZgBmcTA5MwmDVDgQEoCBFiAApChcCCzE1gJazCDIYKEAMCk4WgRrGuUoCymFclQFmJ4WIQBpsoQ2ECRCiAgUcExGDZCiQOOgAJ7wIgARJk2Q5kgARBQiDAL8LwHGrUPwCF8RHZOrcQTwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrocowbell1: {
    name: "Electro Cow Bell",
    url: "sounds/electrocowbell1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrocowbell2: {
    name: "Electro Cow Bell",
    url: "sounds/electrocowbell2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrocowbell3: {
    name: "Electro Cow Bell",
    url: "sounds/electrocowbell3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrokick1: {
    name: "Electro Kick",
    url: "sounds/electrokick1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrokick2: {
    name: "Electro Kick",
    url: "sounds/electrokick2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrokick3: {
    name: "Electro Kick",
    url: "sounds/electrokick3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrosnare1: {
    name: "Electro Snare",
    url: "sounds/electrosnare1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAD1BMVEUAAAAA//8A//8A//8A//+qSDxnAAAABHRSTlMAcGiqfEWlkwAAAB1JREFUCNdjcIEBBmdBCDBhcGKAAJVBwIK7CuFSAFOoDDmYZvvcAAAAAElFTkSuQmCC",
    buffer: null,
  },
  electrosnare2: {
    name: "Electro Snare",
    url: "sounds/electrosnare2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAD1BMVEUAAAAA//8A//8A//8A//+qSDxnAAAABHRSTlMAcGiqfEWlkwAAAB1JREFUCNdjcIEBBmdBCDBhcGKAAJVBwIK7CuFSAFOoDDmYZvvcAAAAAElFTkSuQmCC",
    buffer: null,
  },
  electrosnare3: {
    name: "Electro Snare",
    url: "sounds/electrosnare3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAD1BMVEUAAAAA//8A//8A//8A//+qSDxnAAAABHRSTlMAcGiqfEWlkwAAAB1JREFUCNdjcIEBBmdBCDBhcGKAAJVBwIK7CuFSAFOoDDmYZvvcAAAAAElFTkSuQmCC",
    buffer: null,
  },
  electrotap1: {
    name: "Electro Tap",
    url: "sounds/electrotap1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrotap2: {
    name: "Electro Tap",
    url: "sounds/electrotap2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  electrotap3: {
    name: "Electro Tap",
    url: "sounds/electrotap3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  heel1: {
    name: "Heel",
    url: "sounds/heel1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAh+vluPKgYzoPgXWwfXJAIMyWpkAsHwAAAHxJREFUGNNt0EcSwzAIBVC6Suy4cP+7ZoRiKxqHFbz5CwCi8rowL2uGq4o5CaKQW/lGWFPvknKODB/7la/OLWd6y9tPNYDN0xCE5Bsg/QoAIYhM0maqXV5doFLQkCCRSdqMNAkQxhJDYgkwxSG7Whzk5y0Hl+fZ/5/zfOEHRr4E2ih2GMgAAAAASUVORK5CYII=",
    buffer: null,
  },
  heel2: {
    name: "Heel",
    url: "sounds/heel2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAh+vluPKgYzoPgXWwfXJAIMyWpkAsHwAAAHxJREFUGNNt0EcSwzAIBVC6Suy4cP+7ZoRiKxqHFbz5CwCi8rowL2uGq4o5CaKQW/lGWFPvknKODB/7la/OLWd6y9tPNYDN0xCE5Bsg/QoAIYhM0maqXV5doFLQkCCRSdqMNAkQxhJDYgkwxSG7Whzk5y0Hl+fZ/5/zfOEHRr4E2ih2GMgAAAAASUVORK5CYII=",
    buffer: null,
  },
  heel3: {
    name: "Heel",
    url: "sounds/heel3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAh+vluPKgYzoPgXWwfXJAIMyWpkAsHwAAAHxJREFUGNNt0EcSwzAIBVC6Suy4cP+7ZoRiKxqHFbz5CwCi8rowL2uGq4o5CaKQW/lGWFPvknKODB/7la/OLWd6y9tPNYDN0xCE5Bsg/QoAIYhM0maqXV5doFLQkCCRSdqMNAkQxhJDYgkwxSG7Whzk5y0Hl+fZ/5/zfOEHRr4E2ih2GMgAAAAASUVORK5CYII=",
    buffer: null,
  },
  hihat1: {
    name: "Hi Hat",
    url: "sounds/hihat1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAYFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///9cOicAAAAIHRSTlMAsP3X6SDj3LiomYeEWDgH9vLtycK/opOQfk9KLB0VFCNgIvUAAAB/SURBVBjTvc7HEcMwDETRFcBgikE5p/67tGnZGrEBvQMG80+LaB1aRaTaYcUpdKT7yfup19SFWJaymfEzN+UCBDIFLoWhgJyR4BzCImFFrImc4cSBm0M4SMUbLhsrCUhdjfIMcqz0992tIH59MAm7/9d4Z+raOF/gLsvifSC9AZYBBP/Wc8CzAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hihat2: {
    name: "Hi Hat",
    url: "sounds/hihat2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAYFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///9cOicAAAAIHRSTlMAsP3X6SDj3LiomYeEWDgH9vLtycK/opOQfk9KLB0VFCNgIvUAAAB/SURBVBjTvc7HEcMwDETRFcBgikE5p/67tGnZGrEBvQMG80+LaB1aRaTaYcUpdKT7yfup19SFWJaymfEzN+UCBDIFLoWhgJyR4BzCImFFrImc4cSBm0M4SMUbLhsrCUhdjfIMcqz0992tIH59MAm7/9d4Z+raOF/gLsvifSC9AZYBBP/Wc8CzAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hihat3: {
    name: "Hi Hat",
    url: "sounds/hihat3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAYFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///9cOicAAAAIHRSTlMAsP3X6SDj3LiomYeEWDgH9vLtycK/opOQfk9KLB0VFCNgIvUAAAB/SURBVBjTvc7HEcMwDETRFcBgikE5p/67tGnZGrEBvQMG80+LaB1aRaTaYcUpdKT7yfup19SFWJaymfEzN+UCBDIFLoWhgJyR4BzCImFFrImc4cSBm0M4SMUbLhsrCUhdjfIMcqz0992tIH59MAm7/9d4Z+raOF/gLsvifSC9AZYBBP/Wc8CzAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hihato: {
    name: "Hi Hat",
    url: "sounds/hihato.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAYFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///9cOicAAAAIHRSTlMAsP3X6SDj3LiomYeEWDgH9vLtycK/opOQfk9KLB0VFCNgIvUAAAB/SURBVBjTvc7HEcMwDETRFcBgikE5p/67tGnZGrEBvQMG80+LaB1aRaTaYcUpdKT7yfup19SFWJaymfEzN+UCBDIFLoWhgJyR4BzCImFFrImc4cSBm0M4SMUbLhsrCUhdjfIMcqz0992tIH59MAm7/9d4Z+raOF/gLsvifSC9AZYBBP/Wc8CzAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hihato1: {
    name: "Hi Hat-O",
    url: "sounds/hihato1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAYDshrGAAAAAQSURBVAjXY5jAwMCQQB8SAJaZEOHe+5zxAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hihato2: {
    name: "Hi Hat-O",
    url: "sounds/hihato2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAYDshrGAAAAAQSURBVAjXY5jAwMCQQB8SAJaZEOHe+5zxAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hihato3: {
    name: "Hi Hat-O",
    url: "sounds/hihato3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAYDshrGAAAAAQSURBVAjXY5jAwMCQQB8SAJaZEOHe+5zxAAAAAElFTkSuQmCC",
    buffer: null,
  },
  hup1: {
    name: "Hup",
    url: "sounds/hup1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAJFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9MwLO1AAAAC3RSTlMAUwwSyFjA2o8/PteU34wAAAAvSURBVAjXY2BKm8DAwMCVpsDAvFsAyGLcTR6rNTQ0NALMAgMwq8TFxcUdoY5aLAD6RSSqdii8ugAAAABJRU5ErkJggg==",
    buffer: null,
  },
  hup2: {
    name: "Hup",
    url: "sounds/hup2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAJFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9MwLO1AAAAC3RSTlMAUwwSyFjA2o8/PteU34wAAAAvSURBVAjXY2BKm8DAwMCVpsDAvFsAyGLcTR6rNTQ0NALMAgMwq8TFxcUdoY5aLAD6RSSqdii8ugAAAABJRU5ErkJggg==",
    buffer: null,
  },
  hup3: {
    name: "Hup",
    url: "sounds/hup3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAJFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9MwLO1AAAAC3RSTlMAUwwSyFjA2o8/PteU34wAAAAvSURBVAjXY2BKm8DAwMCVpsDAvFsAyGLcTR6rNTQ0NALMAgMwq8TFxcUdoY5aLAD6RSSqdii8ugAAAABJRU5ErkJggg==",
    buffer: null,
  },
  lowelectronicconga: {
    name: "Low Electro Conga",
    url: "sounds/lowelectronicconga.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF5JREFUCNc1yjEKgDAAQ9Eo6qz0AuLiXMTdQXAVxN0ziOD1myY0Q/jDQ3iQ10XMm6p5Ua2qq0f9qY4RCCejjQChGQjNICgmKCYoJigmaEZ4kxnuZIYLmeFP5g0om/Ilf+oLXCXDmOcAAAAASUVORK5CYII=",
    buffer: null,
  },
  lowfloortom1: {
    name: "Low Floor Tom",
    url: "sounds/lowfloortom1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF5JREFUCNc1yjEKgDAAQ9Eo6qz0AuLiXMTdQXAVxN0ziOD1myY0Q/jDQ3iQ10XMm6p5Ua2qq0f9qY4RCCejjQChGQjNICgmKCYoJigmaEZ4kxnuZIYLmeFP5g0om/Ilf+oLXCXDmOcAAAAASUVORK5CYII=",
    buffer: null,
  },
  lowfloortom2: {
    name: "Low Floor Tom",
    url: "sounds/lowfloortom2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF5JREFUCNc1yjEKgDAAQ9Eo6qz0AuLiXMTdQXAVxN0ziOD1myY0Q/jDQ3iQ10XMm6p5Ua2qq0f9qY4RCCejjQChGQjNICgmKCYoJigmaEZ4kxnuZIYLmeFP5g0om/Ilf+oLXCXDmOcAAAAASUVORK5CYII=",
    buffer: null,
  },
  lowfloortom3: {
    name: "Low Floor Tom",
    url: "sounds/lowfloortom3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF5JREFUCNc1yjEKgDAAQ9Eo6qz0AuLiXMTdQXAVxN0ziOD1myY0Q/jDQ3iQ10XMm6p5Ua2qq0f9qY4RCCejjQChGQjNICgmKCYoJigmaEZ4kxnuZIYLmeFP5g0om/Ilf+oLXCXDmOcAAAAASUVORK5CYII=",
    buffer: null,
  },
  maracas1: {
    name: "Maracas",
    url: "sounds/maracas1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAATlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///4whRTAAAAGXRSTlMAFfjWSQOghHNhOiTw5uXQva6sbWVPQCEOo1M7SwAAAEhJREFUGNNjGBAgwc2IKiDGLCnJJMTCihARkeTnZOFgluRlBytlFORiYBQGy3OxMTGxAeX4eEQRyhnZQSYIiKMay8gN0kF/AABtaAIZIN6JNgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  maracas2: {
    name: "Maracas",
    url: "sounds/maracas2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAATlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///4whRTAAAAGXRSTlMAFfjWSQOghHNhOiTw5uXQva6sbWVPQCEOo1M7SwAAAEhJREFUGNNjGBAgwc2IKiDGLCnJJMTCihARkeTnZOFgluRlBytlFORiYBQGy3OxMTGxAeX4eEQRyhnZQSYIiKMay8gN0kF/AABtaAIZIN6JNgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  maracas3: {
    name: "Maracas",
    url: "sounds/maracas3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAATlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///4whRTAAAAGXRSTlMAFfjWSQOghHNhOiTw5uXQva6sbWVPQCEOo1M7SwAAAEhJREFUGNNjGBAgwc2IKiDGLCnJJMTCihARkeTnZOFgluRlBytlFORiYBQGy3OxMTGxAeX4eEQRyhnZQSYIiKMay8gN0kF/AABtaAIZIN6JNgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  mouth1: {
    name: "Mouth",
    url: "sounds/mouth1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA6bSmgkISPUsxkewAAABRSURBVAjXY2BgYHUSVAlgAAI2i46OjuYEIKuwAwTEgUISYFZjAgNzBwQYMERAWa0MHlBWC4MGlNXEIAFlNSJYCFmEDoQpCJMRtiFcgHAVwqUAfTBAJyhACe0AAAAASUVORK5CYII=",
    buffer: null,
  },
  mouth2: {
    name: "Mouth",
    url: "sounds/mouth2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA6bSmgkISPUsxkewAAABRSURBVAjXY2BgYHUSVAlgAAI2i46OjuYEIKuwAwTEgUISYFZjAgNzBwQYMERAWa0MHlBWC4MGlNXEIAFlNSJYCFmEDoQpCJMRtiFcgHAVwqUAfTBAJyhACe0AAAAASUVORK5CYII=",
    buffer: null,
  },
  mouth3: {
    name: "Mouth",
    url: "sounds/mouth3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA6bSmgkISPUsxkewAAABRSURBVAjXY2BgYHUSVAlgAAI2i46OjuYEIKuwAwTEgUISYFZjAgNzBwQYMERAWa0MHlBWC4MGlNXEIAFlNSJYCFmEDoQpCJMRtiFcgHAVwqUAfTBAJyhACe0AAAAASUVORK5CYII=",
    buffer: null,
  },
  neck1: {
    name: "Neck",
    url: "sounds/neck1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAFHRSTlMAZ0hYu35TIwW1rqibko1gSiwgFuNUgzMAAABUSURBVBjTrcw5DsAgEANAk4Vd7vP/f40iFAVSM4ULyzJOYvXD0PXaVI3csGkZpLBRhKEtFlYPgAwWhp6M9DUU59b4PovuzfsiwaVSkguChTALzrsBO1cB7aZ1tIAAAAAASUVORK5CYII=",
    buffer: null,
  },
  neck2: {
    name: "Neck",
    url: "sounds/neck2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAFHRSTlMAZ0hYu35TIwW1rqibko1gSiwgFuNUgzMAAABUSURBVBjTrcw5DsAgEANAk4Vd7vP/f40iFAVSM4ULyzJOYvXD0PXaVI3csGkZpLBRhKEtFlYPgAwWhp6M9DUU59b4PovuzfsiwaVSkguChTALzrsBO1cB7aZ1tIAAAAAASUVORK5CYII=",
    buffer: null,
  },
  neck3: {
    name: "Neck",
    url: "sounds/neck3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAFHRSTlMAZ0hYu35TIwW1rqibko1gSiwgFuNUgzMAAABUSURBVBjTrcw5DsAgEANAk4Vd7vP/f40iFAVSM4ULyzJOYvXD0PXaVI3csGkZpLBRhKEtFlYPgAwWhp6M9DUU59b4PovuzfsiwaVSkguChTALzrsBO1cB7aZ1tIAAAAAASUVORK5CYII=",
    buffer: null,
  },
  open1: {
    name: "Open",
    url: "sounds/open1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAOVBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///msBf6AAAAEnRSTlMA9/Piw7egkYRAKA/t5tVwbjgX/4UEAAAAZ0lEQVQY022QWQoAIQxD467j7v0PO4xFGGnzVR5paYKtFF2tLiYcZb+0DcHq5TORadSgaSgzt8e05/ifZj6fV0SIKQ+k1fFTXwlR45KOcPZG1qGEG4UiIb4onedP8FflQDw2L0eo8AWqyAP9jB/QxgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  open2: {
    name: "Open",
    url: "sounds/open2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAOVBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///msBf6AAAAEnRSTlMA9/Piw7egkYRAKA/t5tVwbjgX/4UEAAAAZ0lEQVQY022QWQoAIQxD467j7v0PO4xFGGnzVR5paYKtFF2tLiYcZb+0DcHq5TORadSgaSgzt8e05/ifZj6fV0SIKQ+k1fFTXwlR45KOcPZG1qGEG4UiIb4onedP8FflQDw2L0eo8AWqyAP9jB/QxgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  open3: {
    name: "Open",
    url: "sounds/open3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAOVBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A///msBf6AAAAEnRSTlMA9/Piw7egkYRAKA/t5tVwbjgX/4UEAAAAZ0lEQVQY022QWQoAIQxD467j7v0PO4xFGGnzVR5paYKtFF2tLiYcZb+0DcHq5TORadSgaSgzt8e05/ifZj6fV0SIKQ+k1fFTXwlR45KOcPZG1qGEG4UiIb4onedP8FflQDw2L0eo8AWqyAP9jB/QxgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  openhighconga1: {
    name: "Open High Conga",
    url: "sounds/openhighconga1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  openhighconga2: {
    name: "Open High Conga",
    url: "sounds/openhighconga2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  openhighconga3: {
    name: "Open High Conga",
    url: "sounds/openhighconga3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  openhighconga4: {
    name: "Open Conga",
    url: "sounds/openhighconga4.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAGFBMVEUAAAAA//8A//8A//8A//8A//8A//8A///dMCgzAAAAB3RSTlMAwED5lRsd1vko0AAAAF1JREFUCNc1yjEKgDAQRNFR1DqSCwQb60XsLQRbQew9QxC8vpudza9+8VCaUBvrtF/ya5bgN+/ZL97i7MWRyFZcgWxDl8lO9OIMCsmgkAwKyaCQzKAxg8YI42M3yA95jQtcic89QQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  rest: {
    name: "Rest",
    url: "sounds/rest1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAQMAAABsABwUAAAABlBMVEUAAAAA//8bQaswAAAAAnRSTlMAsL3yfrQAAAARSURBVAjXYyAE/v8/AMYEAADGNgV95p299gAAAABJRU5ErkJggg==",
    buffer: null,
  },
  scratch11: {
    name: "Scratch",
    url: "sounds/scratch11.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAZlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+/pmgYAAAAInRSTlMA/si5hAwH+ejgwo9nRCQc8vDt19S0rKOekXp5bltQNCwTKtQZCwAAAJlJREFUGNNVjlcOxCAMRG1CZ4H0Xu9/ybXYKGHfx0h+lkeGxMmLui74CQ+LKq1ztlTLLaTFSQAhJrQyKY4ebjxyIA7F4YGrg3Iw8lXSDJTNCBljQ534ydUHBUTccrVhBNAuV05TdCxXrEvX+2v2X3OhL8oQKC5dpE2sjKcFDd5UERKBYb8ytvbIwvPz3CLRzhIyBGMC/khdN18AKAWRiNssMgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  scratch12: {
    name: "Scratch",
    url: "sounds/scratch12.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAZlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+/pmgYAAAAInRSTlMA/si5hAwH+ejgwo9nRCQc8vDt19S0rKOekXp5bltQNCwTKtQZCwAAAJlJREFUGNNVjlcOxCAMRG1CZ4H0Xu9/ybXYKGHfx0h+lkeGxMmLui74CQ+LKq1ztlTLLaTFSQAhJrQyKY4ebjxyIA7F4YGrg3Iw8lXSDJTNCBljQ534ydUHBUTccrVhBNAuV05TdCxXrEvX+2v2X3OhL8oQKC5dpE2sjKcFDd5UERKBYb8ytvbIwvPz3CLRzhIyBGMC/khdN18AKAWRiNssMgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  scratch13: {
    name: "Scratch",
    url: "sounds/scratch13.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAZlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+/pmgYAAAAInRSTlMA/si5hAwH+ejgwo9nRCQc8vDt19S0rKOekXp5bltQNCwTKtQZCwAAAJlJREFUGNNVjlcOxCAMRG1CZ4H0Xu9/ybXYKGHfx0h+lkeGxMmLui74CQ+LKq1ztlTLLaTFSQAhJrQyKY4ebjxyIA7F4YGrg3Iw8lXSDJTNCBljQ534ydUHBUTccrVhBNAuV05TdCxXrEvX+2v2X3OhL8oQKC5dpE2sjKcFDd5UERKBYb8ytvbIwvPz3CLRzhIyBGMC/khdN18AKAWRiNssMgAAAABJRU5ErkJggg==",
    buffer: null,
  },
  scratch21: {
    name: "Scratch",
    url: "sounds/scratch21.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAKlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8JKBiBAAAADnRSTlMA/mXQwLqwoEwzCPUbDf6xrw4AAABYSURBVAjXYwCBNAYo4HJZAGFwGAoKN4AYvIVBLqriF4As9k1AddoFQFajAsMZBiYJIMsUrDgYqFEIzFJcwMApCWZNnIBgIWQROhCmIExG2IZwAcJVCJcCACITFHW3UmQFAAAAAElFTkSuQmCC",
    buffer: null,
  },
  scratch22: {
    name: "Scratch",
    url: "sounds/scratch22.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAKlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8JKBiBAAAADnRSTlMA/mXQwLqwoEwzCPUbDf6xrw4AAABYSURBVAjXYwCBNAYo4HJZAGFwGAoKN4AYvIVBLqriF4As9k1AddoFQFajAsMZBiYJIMsUrDgYqFEIzFJcwMApCWZNnIBgIWQROhCmIExG2IZwAcJVCJcCACITFHW3UmQFAAAAAElFTkSuQmCC",
    buffer: null,
  },
  scratch23: {
    name: "Scratch",
    url: "sounds/scratch23.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAKlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8JKBiBAAAADnRSTlMA/mXQwLqwoEwzCPUbDf6xrw4AAABYSURBVAjXYwCBNAYo4HJZAGFwGAoKN4AYvIVBLqriF4As9k1AddoFQFajAsMZBiYJIMsUrDgYqFEIzFJcwMApCWZNnIBgIWQROhCmIExG2IZwAcJVCJcCACITFHW3UmQFAAAAAElFTkSuQmCC",
    buffer: null,
  },
  scratch31: {
    name: "Scratch",
    url: "sounds/scratch31.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAilBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8CSwOUAAAALnRSTlMA/vvy2HgFpH1gvbKG7eeglYM7KiEM4tzPy8ismotyTDQR6MbCuLecj2hOS0QSJ3baTgAAAKtJREFUGNNdjlcSwyAMRBHNGLDjEre4pvf7Xy+AU3D0sTN6I+0u+sxqg/4naJb7dK4BaHD/Ap5i2u2rpIbV9k0OWHDnFZLy6RCDh9GQGVmTwJIc9z/TEG5GRcS9oKY1ok5+9qUyEmsfhWBCy36JCoRa6aOE2g6k8BAN5i5smPeBMcjcLeB0RikGZZtKiKFzv1xgAjJHGR3RlURHLVSMNR+p/bR+Qu0iqSe3vADRUwe9VEhBQQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  scratch32: {
    name: "Scratch",
    url: "sounds/scratch32.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAilBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8CSwOUAAAALnRSTlMA/vvy2HgFpH1gvbKG7eeglYM7KiEM4tzPy8ismotyTDQR6MbCuLecj2hOS0QSJ3baTgAAAKtJREFUGNNdjlcSwyAMRBHNGLDjEre4pvf7Xy+AU3D0sTN6I+0u+sxqg/4naJb7dK4BaHD/Ap5i2u2rpIbV9k0OWHDnFZLy6RCDh9GQGVmTwJIc9z/TEG5GRcS9oKY1ok5+9qUyEmsfhWBCy36JCoRa6aOE2g6k8BAN5i5smPeBMcjcLeB0RikGZZtKiKFzv1xgAjJHGR3RlURHLVSMNR+p/bR+Qu0iqSe3vADRUwe9VEhBQQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  scratch33: {
    name: "Scratch",
    url: "sounds/scratch33.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAilBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8CSwOUAAAALnRSTlMA/vvy2HgFpH1gvbKG7eeglYM7KiEM4tzPy8ismotyTDQR6MbCuLecj2hOS0QSJ3baTgAAAKtJREFUGNNdjlcSwyAMRBHNGLDjEre4pvf7Xy+AU3D0sTN6I+0u+sxqg/4naJb7dK4BaHD/Ap5i2u2rpIbV9k0OWHDnFZLy6RCDh9GQGVmTwJIc9z/TEG5GRcS9oKY1ok5+9qUyEmsfhWBCy36JCoRa6aOE2g6k8BAN5i5smPeBMcjcLeB0RikGZZtKiKFzv1xgAjJHGR3RlURHLVSMNR+p/bR+Qu0iqSe3vADRUwe9VEhBQQAAAABJRU5ErkJggg==",
    buffer: null,
  },
  slap1: {
    name: "Slap",
    url: "sounds/slap1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAmdfGvrmik4tnAcKopZ1wX1pC5NHnKAAAAIhJREFUGNNtjksSxCAIREFFjd9E7n/XAao0s0gv5Pm6pIQd9Ju+1UpFzlGVnwU2GMXFIHhzMmVg6tJSo5ihkwxbcVyjKcVfJjt3jPc1BCLH7FqPcSAC4oixN1VEIVS//5f14TQ8ZlLLfB1Rklyow+sKKoYIkPg2Y6DKysfUslGHrVjwxuOmD/UDkJ8FVciAD1kAAAAASUVORK5CYII=",
    buffer: null,
  },
  slap2: {
    name: "Slap",
    url: "sounds/slap2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAmdfGvrmik4tnAcKopZ1wX1pC5NHnKAAAAIhJREFUGNNtjksSxCAIREFFjd9E7n/XAao0s0gv5Pm6pIQd9Ju+1UpFzlGVnwU2GMXFIHhzMmVg6tJSo5ihkwxbcVyjKcVfJjt3jPc1BCLH7FqPcSAC4oixN1VEIVS//5f14TQ8ZlLLfB1Rklyow+sKKoYIkPg2Y6DKysfUslGHrVjwxuOmD/UDkJ8FVciAD1kAAAAASUVORK5CYII=",
    buffer: null,
  },
  slap3: {
    name: "Slap",
    url: "sounds/slap3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAmdfGvrmik4tnAcKopZ1wX1pC5NHnKAAAAIhJREFUGNNtjksSxCAIREFFjd9E7n/XAao0s0gv5Pm6pIQd9Ju+1UpFzlGVnwU2GMXFIHhzMmVg6tJSo5ihkwxbcVyjKcVfJjt3jPc1BCLH7FqPcSAC4oixN1VEIVS//5f14TQ8ZlLLfB1Rklyow+sKKoYIkPg2Y6DKysfUslGHrVjwxuOmD/UDkJ8FVciAD1kAAAAASUVORK5CYII=",
    buffer: null,
  },
  splash1: {
    name: "Splash",
    url: "sounds/splash1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAcCaWvAQAAAAYSURBVAjXY1gFBAsYQoEggIEGAGIyxBYAFFYJ2XxZQYEAAAAASUVORK5CYII=",
    buffer: null,
  },
  splash2: {
    name: "Splash",
    url: "sounds/splash2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAcCaWvAQAAAAYSURBVAjXY1gFBAsYQoEggIEGAGIyxBYAFFYJ2XxZQYEAAAAASUVORK5CYII=",
    buffer: null,
  },
  splash3: {
    name: "Splash",
    url: "sounds/splash3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAcCaWvAQAAAAYSURBVAjXY1gFBAsYQoEggIEGAGIyxBYAFFYJ2XxZQYEAAAAASUVORK5CYII=",
    buffer: null,
  },
  tamborine1: {
    name: "Tamborine",
    url: "sounds/tamborine1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAASFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8c4xNnAAAAF3RSTlMABYeskIzlyZpVVEosEfj39ddvXkAjG6pfJCYAAABoSURBVBjTdZBXDoAwDENLB6tlj3f/m1IBRVQBf0VPThRb3ermVeXaB3A5csC4vUChOaWLh1RY00+Lo0pM4+P9OHj05WmwyW9poi+U0CbUQhlUDZiEDFB/Ibkoz8sn5KsykIj9X46s8AAl0gezYroRXwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  tamborine2: {
    name: "Tamborine",
    url: "sounds/tamborine2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAASFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8c4xNnAAAAF3RSTlMABYeskIzlyZpVVEosEfj39ddvXkAjG6pfJCYAAABoSURBVBjTdZBXDoAwDENLB6tlj3f/m1IBRVQBf0VPThRb3ermVeXaB3A5csC4vUChOaWLh1RY00+Lo0pM4+P9OHj05WmwyW9poi+U0CbUQhlUDZiEDFB/Ibkoz8sn5KsykIj9X46s8AAl0gezYroRXwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  tamborine3: {
    name: "Tamborine",
    url: "sounds/tamborine3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAASFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8c4xNnAAAAF3RSTlMABYeskIzlyZpVVEosEfj39ddvXkAjG6pfJCYAAABoSURBVBjTdZBXDoAwDENLB6tlj3f/m1IBRVQBf0VPThRb3ermVeXaB3A5csC4vUChOaWLh1RY00+Lo0pM4+P9OHj05WmwyW9poi+U0CbUQhlUDZiEDFB/Ibkoz8sn5KsykIj9X46s8AAl0gezYroRXwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  tip1: {
    name: "Tip",
    url: "sounds/tip1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAIVBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A///D36StAAAAC3RSTlMAqrgmoi0vnzDGkGe3ricAAABeSURBVAjXYwCBUAYYEIQxWMsDoCxGYwEoK52hDMoSZjCEMNgcGFgSIMoMGJghCluA2AOqjAGikMMBSLA0QJQxQBSmgJW4QZRBFLI6gFksAWBlEIUhUCtdGVYqQcAsAPQECjvyrOZZAAAAAElFTkSuQmCC",
    buffer: null,
  },
  tip2: {
    name: "Tip",
    url: "sounds/tip2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAIVBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A///D36StAAAAC3RSTlMAqrgmoi0vnzDGkGe3ricAAABeSURBVAjXYwCBUAYYEIQxWMsDoCxGYwEoK52hDMoSZjCEMNgcGFgSIMoMGJghCluA2AOqjAGikMMBSLA0QJQxQBSmgJW4QZRBFLI6gFksAWBlEIUhUCtdGVYqQcAsAPQECjvyrOZZAAAAAElFTkSuQmCC",
    buffer: null,
  },
  tip3: {
    name: "Tip",
    url: "sounds/tip3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAIVBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A///D36StAAAAC3RSTlMAqrgmoi0vnzDGkGe3ricAAABeSURBVAjXYwCBUAYYEIQxWMsDoCxGYwEoK52hDMoSZjCEMNgcGFgSIMoMGJghCluA2AOqjAGikMMBSLA0QJQxQBSmgJW4QZRBFLI6gFksAWBlEIUhUCtdGVYqQcAsAPQECjvyrOZZAAAAAElFTkSuQmCC",
    buffer: null,
  },
  tube1: {
    name: "Tube",
    url: "sounds/tube1.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  tube2: {
    name: "Tube",
    url: "sounds/tube2.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  tube3: {
    name: "Tube",
    url: "sounds/tube3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "trap-cymbal-03": {
    name: "Trap Cymbal",
    url: "sounds/trap-cymbal-03.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "trap-cymbal-06": {
    name: "Trap Cymbal",
    url: "sounds/trap-cymbal-06.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "snare-w-reverb3": {
    name: "Reverb Snare",
    url: "sounds/snare-w-reverb3.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA2L2MiTf5BmDht94AAABGSURBVAjXY0gUhAAxBgEGCGBEZYUouUJYxR0dHeZglgWQ1QxisXaAQACQxQJmOQBZTGCWAoKFkEXogJuCMBnVNky3IFwKAOR6HvMp4o8LAAAAAElFTkSuQmCC",
    buffer: null,
  },
  "hi-hat-reverb": {
    name: "Electro Hi Hat",
    url: "sounds/hi-hat-reverb.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAYDshrGAAAAAQSURBVAjXY5jAwMCQQB8SAJaZEOHe+5zxAAAAAElFTkSuQmCC",
    buffer: null,
  },
  "bass-drum-reverb": {
    name: "Bass Reverb",
    url: "sounds/bass-drum-reverb.wav",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "orchestra-hit": {
    name: "Orchestra Hit",
    url: "sounds/Orchestra-Hit-Party.mp3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAQlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//9t/U3zAAAAFXRSTlMA7rSDBfnm4rysoIp4d1dAKBkPwzgd4rpNAAAAf0lEQVQY021QSQ7EMAgzgez7tPz/q6M26inhBJaxbOOdzobIcMc3v6TOMBun6beQ21NbWyN/vxx/TYwaYx2Yl394iaYUSyGQLTIpAV0bimYBJGtB0w52GDYvrWwHHMMYVJIFCdXnJkYMn50QwXSC9seT/G5it3oOtMfeyzlU+AfT+gc5/8Vy8AAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "afghanistan-rabab": {
    name: "Afghanistan Rabab",
    url: "sounds/Afghanistan-Rabab-.mp3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAASFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8c4xNnAAAAF3RSTlMABYeskIzlyZpVVEosEfj39ddvXkAjG6pfJCYAAABoSURBVBjTdZBXDoAwDENLB6tlj3f/m1IBRVQBf0VPThRb3ermVeXaB3A5csC4vUChOaWLh1RY00+Lo0pM4+P9OHj05WmwyW9poi+U0CbUQhlUDZiEDFB/Ibkoz8sn5KsykIj9X46s8AAl0gezYroRXwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "ambition-string": {
    name: "Ambition String",
    url: "sounds/Ambition-String-_Abrupt_.mp3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAAG1BMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8czg7/AAAACHRSTlMA6bSmgkISPUsxkewAAABRSURBVAjXY2BgYHUSVAlgAAI2i46OjuYEIKuwAwTEgUISYFZjAgNzBwQYMERAWa0MHlBWC4MGlNXEIAFlNSJYCFmEDoQpCJMRtiFcgHAVwqUAfTBAJyhACe0AAAAASUVORK5CYII=",
    buffer: null,
  },
  "cali-wah-guitar": {
    name: "Cali Wah Guitar",
    url: "sounds/Cali-Wah-Guitar.mp3",
    icon: "img/electricsnare.png",
    buffer: null,
  },
  "low-sway-futuristic": {
    name: "Low Sway Futuristic",
    url: "sounds/Low-Sway-Futuristic.mp3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAANlBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//+B7e77AAAAEXRSTlMAyJj46+HbkGAMOubQw78FQ1x+ta0AAABNSURBVBjT1cjJAYAgDADBQC4Jl+m/WVE+oQT3sY+BnSmzGoQMRVXwDlSpABSqgQhfQgrUHHtHb4GSsDtLipRhTsgnrf2ExrUaB/nXpgeuqwJLCYEENwAAAABJRU5ErkJggg==",
    buffer: null,
  },
  "moonlit-bass": {
    name: "Moonlit Bass",
    url: "sounds/Moonlit-Sky-Bass-_short_.mp3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAMAAABhEH5lAAAAPFBMVEUAAAAA//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//831goXAAAAE3RSTlMAh+vluPKgYzoPgXWwfXJAIMyWpkAsHwAAAHxJREFUGNNt0EcSwzAIBVC6Suy4cP+7ZoRiKxqHFbz5CwCi8rowL2uGq4o5CaKQW/lGWFPvknKODB/7la/OLWd6y9tPNYDN0xCE5Bsg/QoAIYhM0maqXV5doFLQkCCRSdqMNAkQxhJDYgkwxSG7Whzk5y0Hl+fZ/5/zfOEHRr4E2ih2GMgAAAAASUVORK5CYII=",
    buffer: null,
  },
  "night-funk": {
    name: "Night Funk",
    url: "sounds/Night-Funk-Bass.mp3",
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASAgMAAAAroGbEAAAACVBMVEUAAAAA//8A//8pJDpCAAAAAnRSTlMAYDshrGAAAAAQSURBVAjXY5jAwMCQQB8SAJaZEOHe+5zxAAAAAElFTkSuQmCC",
    buffer: null,
  },
};

console.log(Object.keys(catalog).length + " sounds to load");
