const catalog = {
  'acousticbass1': {
    name: 'Acoustic Bass',
    url: 'sounds/acousticbass1.wav',
    icon: 'images/acousticbass.png',
    buffer: null,
  },
  'acousticbass2': {
    name: 'Acoustic Bass',
    url: 'sounds/acousticbass2.wav',
    icon: 'images/acousticbass.png',
    buffer: null,
  },
  'acousticbass3': {
    name: 'Acoustic Bass',
    url: 'sounds/acousticbass3.wav',
    icon: 'images/acousticbass.png',
    buffer: null,
  },
  'acousticsnare1': {
    name: 'Acoustic Snare',
    url: 'sounds/acousticsnare1.wav',
    icon: 'images/acousticsnare.png',
    buffer: null,
  },
  'acousticsnare2': {
    name: 'Acoustic Snare',
    url: 'sounds/acousticsnare2.wav',
    icon: 'images/acousticsnare.png',
    buffer: null,
  },
  'acousticsnare3': {
    name: 'Acoustic Snare',
    url: 'sounds/acousticsnare3.wav',
    icon: 'images/acousticsnare.png',
    buffer: null,
  },
  'bassdrum1': {
    name: 'Bass Drum',
    url: 'sounds/bassdrum1.wav',
    icon: 'images/bassdrum.png',
    buffer: null,
  },
  'bassdrum2': {
    name: 'Bass Drum',
    url: 'sounds/bassdrum2.wav',
    icon: 'images/bassdrum.png',
    buffer: null,
  },
  'bassdrum3': {
    name: 'Bass Drum',
    url: 'sounds/bassdrum3.wav',
    icon: 'images/bassdrum.png',
    buffer: null,
  },
  'blank1': {
    name: 'Blank',
    url: 'sounds/blank1.wav',
    icon: 'images/blank.png',
    buffer: null,
  },
  'blank2': {
    name: 'Blank',
    url: 'sounds/blank2.wav',
    icon: 'images/blank.png',
    buffer: null,
  },
  'blank3': {
    name: 'Blank',
    url: 'sounds/blank3.wav',
    icon: 'images/blank.png',
    buffer: null,
  },
  'blank4': {
    name: 'Blank',
    url: 'sounds/blank4.wav',
    icon: 'images/blank.png',
    buffer: null,
  },
  'clap1': {
    name: 'Clap',
    url: 'sounds/clap1.wav',
    icon: 'images/clap.png',
    buffer: null,
  },
  'clap2': {
    name: 'Clap',
    url: 'sounds/clap2.wav',
    icon: 'images/clap.png',
    buffer: null,
  },
  'clap3': {
    name: 'Clap',
    url: 'sounds/clap3.wav',
    icon: 'images/clap.png',
    buffer: null,
  },
  'clap4': {
    name: 'Clap',
    url: 'sounds/clap4.wav',
    icon: 'images/clap.png',
    buffer: null,
  },
  'clave1': {
    name: 'Clave',
    url: 'sounds/clave1.wav',
    icon: 'images/clave.png',
    buffer: null,
  },
  'clave2': {
    name: 'Clave',
    url: 'sounds/clave2.wav',
    icon: 'images/clave.png',
    buffer: null,
  },
  'clave3': {
    name: 'Clave',
    url: 'sounds/clave3.wav',
    icon: 'images/clave.png',
    buffer: null,
  },
  'congaslap': {
    name: 'Conga Slap',
    url: 'sounds/congaslap.wav',
    icon: 'images/slap.png',
    buffer: null,
  },
  'crash1': {
    name: 'Crash',
    url: 'sounds/crash1.wav',
    icon: 'images/crash.png',
    buffer: null,
  },
  'crash2': {
    name: 'Crash',
    url: 'sounds/crash2.wav',
    icon: 'images/crash.png',
    buffer: null,
  },
  'crash3': {
    name: 'Crash',
    url: 'sounds/crash3.wav',
    icon: 'images/crash.png',
    buffer: null,
  },
  'electricsnare1': {
    name: 'Electric Snare',
    url: 'sounds/electricsnare1.wav',
    icon: 'images/electricsnare.png',
    buffer: null,
  },
  'electricsnare2': {
    name: 'Electric Snare',
    url: 'sounds/electricsnare2.wav',
    icon: 'images/electricsnare.png',
    buffer: null,
  },
  'electricsnare3': {
    name: 'Electric Snare',
    url: 'sounds/electricsnare3.wav',
    icon: 'images/electricsnare.png',
    buffer: null,
  },
  'electroclap1': {
    name: 'Electro Clap',
    url: 'sounds/electroclap1.wav',
    icon: 'images/electroclap.png',
    buffer: null,
  },
  'electroclap2': {
    name: 'Electro Clap',
    url: 'sounds/electroclap2.wav',
    icon: 'images/electroclap.png',
    buffer: null,
  },
  'electroclap3': {
    name: 'Electro Clap',
    url: 'sounds/electroclap3.wav',
    icon: 'images/electroclap.png',
    buffer: null,
  },
  'electrocowbell1': {
    name: 'Electro Cow Bell',
    url: 'sounds/electrocowbell1.wav',
    icon: 'images/electrocowbell.png',
    buffer: null,
  },
  'electrocowbell2': {
    name: 'Electro Cow Bell',
    url: 'sounds/electrocowbell2.wav',
    icon: 'images/electrocowbell.png',
    buffer: null,
  },
  'electrocowbell3': {
    name: 'Electro Cow Bell',
    url: 'sounds/electrocowbell3.wav',
    icon: 'images/electrocowbell.png',
    buffer: null,
  },
  'electrokick1': {
    name: 'Electro Kick',
    url: 'sounds/electrokick1.wav',
    icon: 'images/electrokick.png',
    buffer: null,
  },
  'electrokick2': {
    name: 'Electro Kick',
    url: 'sounds/electrokick2.wav',
    icon: 'images/electrokick.png',
    buffer: null,
  },
  'electrokick3': {
    name: 'Electro Kick',
    url: 'sounds/electrokick3.wav',
    icon: 'images/electrokick.png',
    buffer: null,
  },
  'electrosnare1': {
    name: 'Electro Snare',
    url: 'sounds/electrosnare1.wav',
    icon: 'images/electrosnare.png',
    buffer: null,
  },
  'electrosnare2': {
    name: 'Electro Snare',
    url: 'sounds/electrosnare2.wav',
    icon: 'images/electrosnare.png',
    buffer: null,
  },
  'electrosnare3': {
    name: 'Electro Snare',
    url: 'sounds/electrosnare3.wav',
    icon: 'images/electrosnare.png',
    buffer: null,
  },
  'electrotap1': {
    name: 'Electro Tap',
    url: 'sounds/electrotap1.wav',
    icon: 'images/electrotap.png',
    buffer: null,
  },
  'electrotap2': {
    name: 'Electro Tap',
    url: 'sounds/electrotap2.wav',
    icon: 'images/electrotap.png',
    buffer: null,
  },
  'electrotap3': {
    name: 'Electro Tap',
    url: 'sounds/electrotap3.wav',
    icon: 'images/electrotap.png',
    buffer: null,
  },
  'heel1': {
    name: 'Heel',
    url: 'sounds/heel1.wav',
    icon: 'images/heel.png',
    buffer: null,
  },
  'heel2': {
    name: 'Heel',
    url: 'sounds/heel2.wav',
    icon: 'images/heel.png',
    buffer: null,
  },
  'heel3': {
    name: 'Heel',
    url: 'sounds/heel3.wav',
    icon: 'images/heel.png',
    buffer: null,
  },
  'hihat1': {
    name: 'Hi Hat',
    url: 'sounds/hihat1.wav',
    icon: 'images/hihat.png',
    buffer: null,
  },
  'hihat2': {
    name: 'Hi Hat',
    url: 'sounds/hihat2.wav',
    icon: 'images/hihat.png',
    buffer: null,
  },
  'hihat3': {
    name: 'Hi Hat',
    url: 'sounds/hihat3.wav',
    icon: 'images/hihat.png',
    buffer: null,
  },
  'hihato': {
    name: 'Hi Hat',
    url: 'sounds/hihato.wav',
    icon: 'images/hihat.png',
    buffer: null,
  },
  'hihato1': {
    name: 'Hi Hat-O',
    url: 'sounds/hihato1.wav',
    icon: 'images/hihato.png',
    buffer: null,
  },
  'hihato2': {
    name: 'Hi Hat-O',
    url: 'sounds/hihato2.wav',
    icon: 'images/hihato.png',
    buffer: null,
  },
  'hihato3': {
    name: 'Hi Hat-O',
    url: 'sounds/hihato3.wav',
    icon: 'images/hihato.png',
    buffer: null,
  },
  'hup1': {
    name: 'Hup',
    url: 'sounds/hup1.wav',
    icon: 'images/hup.png',
    buffer: null,
  },
  'hup2': {
    name: 'Hup',
    url: 'sounds/hup2.wav',
    icon: 'images/hup.png',
    buffer: null,
  },
  'hup3': {
    name: 'Hup',
    url: 'sounds/hup3.wav',
    icon: 'images/hup.png',
    buffer: null,
  },
  'lowelectronicconga': {
    name: 'Low Electro Conga',
    url: 'sounds/lowelectronicconga.wav',
    icon: 'images/lowfloortom.png',
    buffer: null,
  },
  'lowfloortom1': {
    name: 'Low Floor Tom',
    url: 'sounds/lowfloortom1.wav',
    icon: 'images/lowfloortom.png',
    buffer: null,
  },
  'lowfloortom2': {
    name: 'Low Floor Tom',
    url: 'sounds/lowfloortom2.wav',
    icon: 'images/lowfloortom.png',
    buffer: null,
  },
  'lowfloortom3': {
    name: 'Low Floor Tom',
    url: 'sounds/lowfloortom3.wav',
    icon: 'images/lowfloortom.png',
    buffer: null,
  },
  'maracas1': {
    name: 'Maracas',
    url: 'sounds/maracas1.wav',
    icon: 'images/maracas.png',
    buffer: null,
  },
  'maracas2': {
    name: 'Maracas',
    url: 'sounds/maracas2.wav',
    icon: 'images/maracas.png',
    buffer: null,
  },
  'maracas3': {
    name: 'Maracas',
    url: 'sounds/maracas3.wav',
    icon: 'images/maracas.png',
    buffer: null,
  },
  'mouth1': {
    name: 'Mouth',
    url: 'sounds/mouth1.wav',
    icon: 'images/mouth.png',
    buffer: null,
  },
  'mouth2': {
    name: 'Mouth',
    url: 'sounds/mouth2.wav',
    icon: 'images/mouth.png',
    buffer: null,
  },
  'mouth3': {
    name: 'Mouth',
    url: 'sounds/mouth3.wav',
    icon: 'images/mouth.png',
    buffer: null,
  },
  'neck1': {
    name: 'Neck',
    url: 'sounds/neck1.wav',
    icon: 'images/neck.png',
    buffer: null,
  },
  'neck2': {
    name: 'Neck',
    url: 'sounds/neck2.wav',
    icon: 'images/neck.png',
    buffer: null,
  },
  'neck3': {
    name: 'Neck',
    url: 'sounds/neck3.wav',
    icon: 'images/neck.png',
    buffer: null,
  },
  'open1': {
    name: 'Open',
    url: 'sounds/open1.wav',
    icon: 'images/open.png',
    buffer: null,
  },
  'open2': {
    name: 'Open',
    url: 'sounds/open2.wav',
    icon: 'images/open.png',
    buffer: null,
  },
  'open3': {
    name: 'Open',
    url: 'sounds/open3.wav',
    icon: 'images/open.png',
    buffer: null,
  },
  'openhighconga1': {
    name: 'Open High Conga',
    url: 'sounds/openhighconga1.wav',
    icon: 'images/openhighconga.png',
    buffer: null,
  },
  'openhighconga2': {
    name: 'Open High Conga',
    url: 'sounds/openhighconga2.wav',
    icon: 'images/openhighconga.png',
    buffer: null,
  },
  'openhighconga3': {
    name: 'Open High Conga',
    url: 'sounds/openhighconga3.wav',
    icon: 'images/openhighconga.png',
    buffer: null,
  },
  'openhighconga4': {
    name: 'Open Conga',
    url: 'sounds/openhighconga4.wav',
    icon: 'images/openhighconga.png',
    buffer: null,
  },
  'rest': {
    name: 'Rest',
    url: 'sounds/rest1.wav',
    icon: 'images/rest.png',
    buffer: null,
  },
  'scratch11': {
    name: 'Scratch',
    url: 'sounds/scratch11.wav',
    icon: 'images/scratch1.png',
    buffer: null,
  },
  'scratch12': {
    name: 'Scratch',
    url: 'sounds/scratch12.wav',
    icon: 'images/scratch1.png',
    buffer: null,
  },
  'scratch13': {
    name: 'Scratch',
    url: 'sounds/scratch13.wav',
    icon: 'images/scratch1.png',
    buffer: null,
  },
  'scratch21': {
    name: 'Scratch',
    url: 'sounds/scratch21.wav',
    icon: 'images/scratch2.png',
    buffer: null,
  },
  'scratch22': {
    name: 'Scratch',
    url: 'sounds/scratch22.wav',
    icon: 'images/scratch2.png',
    buffer: null,
  },
  'scratch23': {
    name: 'Scratch',
    url: 'sounds/scratch23.wav',
    icon: 'images/scratch2.png',
    buffer: null,
  },
  'scratch31': {
    name: 'Scratch',
    url: 'sounds/scratch31.wav',
    icon: 'images/scratch3.png',
    buffer: null,
  },
  'scratch32': {
    name: 'Scratch',
    url: 'sounds/scratch32.wav',
    icon: 'images/scratch3.png',
    buffer: null,
  },
  'scratch33': {
    name: 'Scratch',
    url: 'sounds/scratch33.wav',
    icon: 'images/scratch3.png',
    buffer: null,
  },
  'slap1': {
    name: 'Slap',
    url: 'sounds/slap1.wav',
    icon: 'images/slap.png',
    buffer: null,
  },
  'slap2': {
    name: 'Slap',
    url: 'sounds/slap2.wav',
    icon: 'images/slap.png',
    buffer: null,
  },
  'slap3': {
    name: 'Slap',
    url: 'sounds/slap3.wav',
    icon: 'images/slap.png',
    buffer: null,
  },
  'splash1': {
    name: 'Splash',
    url: 'sounds/splash1.wav',
    icon: 'images/splash.png',
    buffer: null,
  },
  'splash2': {
    name: 'Splash',
    url: 'sounds/splash2.wav',
    icon: 'images/splash.png',
    buffer: null,
  },
  'splash3': {
    name: 'Splash',
    url: 'sounds/splash3.wav',
    icon: 'images/splash.png',
    buffer: null,
  },
  'tamborine1': {
    name: 'Tamborine',
    url: 'sounds/tamborine1.wav',
    icon: 'images/tamborine.png',
    buffer: null,
  },
  'tamborine2': {
    name: 'Tamborine',
    url: 'sounds/tamborine2.wav',
    icon: 'images/tamborine.png',
    buffer: null,
  },
  'tamborine3': {
    name: 'Tamborine',
    url: 'sounds/tamborine3.wav',
    icon: 'images/tamborine.png',
    buffer: null,
  },
  'tip1': {
    name: 'Tip',
    url: 'sounds/tip1.wav',
    icon: 'images/tip.png',
    buffer: null,
  },
  'tip2': {
    name: 'Tip',
    url: 'sounds/tip2.wav',
    icon: 'images/tip.png',
    buffer: null,
  },
  'tip3': {
    name: 'Tip',
    url: 'sounds/tip3.wav',
    icon: 'images/tip.png',
    buffer: null,
  },
  'tube1': {
    name: 'Tube',
    url: 'sounds/tube1.wav',
    icon: 'images/tube.png',
    buffer: null,
  },
  'tube2': {
    name: 'Tube',
    url: 'sounds/tube2.wav',
    icon: 'images/tube.png',
    buffer: null,
  },
  'tube3': {
    name: 'Tube',
    url: 'sounds/tube3.wav',
    icon: 'images/tube.png',
    buffer: null,
  },
  'trap-cymbal-03': {
    name: 'Trap Cymbal 3',
    url: 'sounds/trap-cymbal-03.wav',
    icon: 'images/tube.png',
    buffer: null,
  },
  'trap-cymbal-06': {
    name: 'Trap Cymbal 6',
    url: 'sounds/trap-cymbal-06.wav',
    icon: 'images/tube.png',
    buffer: null,
  },
  'snare-w-reverb3': {
    name: 'Snare',
    url: 'sounds/snare-w-reverb3.wav',
    icon: 'images/acousticsnare.png',
    buffer: null,
  },
  'hi-hat-reverb': {
    name: 'Hi Hat',
    url: 'sounds/hi-hat-reverb.wav',
    icon: 'images/hihato.png',
    buffer: null,
  },
  'bass-drum-reverb': {
    name: 'Bass Drum',
    url: 'sounds/bass-drum-reverb.wav',
    icon: 'images/bassdrum.png',
    buffer: null,
  },
};

console.log(Object.keys(catalog).length + ' sounds to load');
